### ISSUE TITLE
How to get all coupons with relation (redeemer)

### ISSUE THREAD

**Issue by stanley-hypo** [michael-rubel/laravel-couponables#3]
I want to get all coupons with redeemer

like:
Coupon::with(['redeemer'])->get();

thanks.

**Comment by michael-rubel** [comment]
Hi @stanley-hypo 

I noticed the inconsistency in the `DefinesModelRelations` trait, as this trait was supposed to define relations, not the concrete models. The fix is PRed already and would ship in the next major release of the package. Delay is because it is a breaking change for those who override that method. For now, I recommend creating a separate model, and extend from `MichaelRubel\Couponables\Models\Coupon`, then add a method:

```php
public function redeemerRelation(): MorphTo
{
    return $this->morphTo();
}
```

And you'll able to eager load it:
```php
$coupons = Coupon::with('redeemerRelation')->get();
```

I hope this helps! 🙂

**Comment by stanley-hypo** [comment]
thanks so much
